name: Wireguard Test
on:
  workflow_dispatch
jobs:
    connect-and-execute:
        permissions:
          contents: 'read'
          id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - id: 'get-orig-ip'
              run: 'curl https://api.ipify.org'    
            - name: Set up WireGuard
              uses: egor-tensin/setup-wireguard@v1
              with:
                endpoint: 35.209.90.76:51821
                endpoint_public_key: LoV84Pfphri6V0tcwrrNdRysDwbxxoPsICT7bFN9DXo=
                ips: 100.64.1.3/24
                allowed_ips: 64.185.227.156/32, 173.231.16.76/32, 104.237.62.211/32, 104.197.79.200/32
                private_key: 8BvASQ7pslnu2OLy7H1UzZ9qSp+DsR2QH1j19T9iGV0=
                preshared_key: rOmqPKUJrQOApcT224ssc3qR05jpjtoocqsyOwVmHZc=
            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                workload_identity_provider: 'projects/77311239361/locations/global/workloadIdentityPools/github-actions-test-pool/providers/github'
                service_account: 'ghactions@veeps-stg.iam.gserviceaccount.com'
                token_format: 'access_token'
            - id: 'setup-gcloud'
              uses: 'google-github-actions/setup-gcloud@v1'
              with:
                version: '363.0.0'
                project_id: 'veeps-stg'
            - id: 'get-credentials'
              uses: 'google-github-actions/get-gke-credentials@v1'
              with:
                cluster_name: 'develop'
                location: 'us-central1-c'
            - id: 'get-ip'
              run: 'curl https://api.ipify.org'            
            - id: 'get-pods'
              run: 'kubectl get pods'
            - id: 'setup-helm'
              uses: azure/setup-helm@v1
              with:
                version: 'v3.5.4'
            - id: 'run-helm-ls'
              run: 'helm ls -n develop'
